main:
  - name: Basics
    identifier: Basics
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
        
  - name: Languages
    identifier: Languages
    weight: 2
    params:
      icon:
        vendor: bs
        name: book

  - name: Advanced
    identifier: Advanced
    weight: 3
    params:
      icon:
        vendor: bs
        name: book

  - name: Applied
    identifier: Applied
    weight: 4
    params:
      icon:
        vendor: bs
        name: book

  - name: Domains
    identifier: Domains
    weight: 4
    params:
      icon:
        vendor: bs
        name: book

  - name: Emerging
    identifier: Emerging
    weight: 4
    params:
      icon:
        vendor: bs
        name: book

  - name: Special
    identifier: Special
    weight: 4
    params:
      icon:
        vendor: bs
        name: book

