main:
  - name: Basics
    identifier: Basics
    weight: 1
    params:
      icon:
        vendor: fas
        name: book-open
  - name: Languages
    identifier: Languages
    weight: 2
    params:
      icon:
        vendor: fas
        name: code
  - name: Advanced
    identifier: Advanced
    weight: 3
    params:
      icon:
        vendor: fas
        name: layer-group
  - name: Applied
    identifier: Applied
    weight: 4
    params:
      icon:
        vendor: fas
        name: wrench
  - name: Domains
    identifier: Domains
    weight: 5
    params:
      icon:
        vendor: fas
        name: shapes
  - name: Emerging
    identifier: Emerging
    weight: 6
    params:
      icon:
        vendor: fas
        name: rocket
  - name: Special
    identifier: Special
    weight: 7
    params:
      icon:
        vendor: fas
        name: gem